name: Create a new release

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
    - run: npm install

    - name: Build bundle with webpack in release mode
    - run: npm run build-release
