name: Create a new release

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build the project
      run: npm install && npm run build-release

    - name: Push it to release repository
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'build/widget.js'
        destination_repo: 'sisypheus/babble-widget-release'
        destination_folder: '.'
        user_email: 'CICD'
        user_name: 'CICD'
        commit_message: 'CICD: New release'
        destination_branch: 'master'
