name: Create a new release

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build release and push it
      run: |
        npm run build-release
        git config user.name "CI/CD"
        git config user.email "CI/CD"
        git add build -f
        git commit -am "Build release"
        git push
